/** Chinese copy for PDP / PLP — keyed by msgKey (m01–m12). */
export type ProductZh = {
  name: string;
  description: string;
  highlights: string[];
  leadTime: string;
  finish: string;
  size: string;
  material: string;
  installation: string;
  categoryName: string;
  specs: Array<{ label: string; value: string }>;
};

export const productsZh: Record<string, ProductZh> = {
  m01: {
    name: "单玻透明 Shaker 室内门 — 底漆（门板 / RapidHang™）",
    description:
      "热销款：Shaker 框线 + 透明玻璃，专业渠道同款外观，工厂直发定价。适合走廊与书房借光。",
    highlights: [
      "走廊与办公区借光同时保持空间分隔",
      "RapidHang™ 包装更紧凑，优于传统整套预挂托盘运输",
      "玻璃出厂覆膜保护，油漆干透后再撕",
    ],
    leadTime: "6–8 个工作日",
    finish: "工厂底漆，可现场涂刷",
    size: "门宽 24″–36″，更大尺寸请询价",
    material: "工程实木芯",
    installation: "单板或 RapidHang™ 预挂",
    categoryName: "室内门",
    specs: [
      { label: "SKU", value: "DTD-INT-M01" },
      { label: "款式", value: "单玻 Shaker" },
      { label: "素材系列", value: "门1" },
      { label: "处理周期", value: "6–8 个工作日" },
    ],
  },
  m02: {
    name: "双面板传统款 — 底漆",
    description: "经典双面板，适合卧室与次卧 — 全屋统一涂刷即可焕新。",
    highlights: ["整屋更换高频 SKU", "标准锁孔开槽", "6 樘以上有批量价"],
    leadTime: "6–8 个工作日",
    finish: "细腻底漆",
    size: "标准门高与预挂高度",
    material: "实木芯",
    installation: "单板或 RapidHang™",
    categoryName: "室内门",
    specs: [
      { label: "SKU", value: "DTD-INT-M02" },
      { label: "款式", value: "双面板" },
      { label: "素材系列", value: "门2" },
      { label: "处理周期", value: "6–8 个工作日" },
    ],
  },
  m03: {
    name: "平板现代款 — 底漆",
    description: "极简立面，适合当代户型 — 从套线到门扇线条干净。",
    highlights: ["公寓与 ADU 友好", "楼梯与窄过道搬运更轻", "可配隐形铰链（五金另购）"],
    leadTime: "6–8 个工作日",
    finish: "光滑底漆",
    size: "常见 28″–32″",
    material: "工程芯材",
    installation: "单板",
    categoryName: "室内门",
    specs: [
      { label: "SKU", value: "DTD-INT-M03" },
      { label: "款式", value: "平板" },
      { label: "素材系列", value: "门3" },
      { label: "处理周期", value: "6–8 个工作日" },
    ],
  },
  m04: {
    name: "Craftsman 入户门 — 预挂系统",
    description: "外立面层次清晰，可按需配置侧光 / 顶窗 — 翻新与新建皆宜。",
    highlights: ["注重耐候的组装方式", "长途可打木箱", "多门项目享 Pro Partner 价"],
    leadTime: "7–10 个工作日",
    finish: "底漆或实木着色（请注明）",
    size: "3′0″ × 6′8″，其它尺寸询价",
    material: "加强型入户结构",
    installation: "预挂 + 密封条选项",
    categoryName: "室外门（入户）",
    specs: [
      { label: "SKU", value: "DTD-EXT-M04" },
      { label: "款式", value: "Craftsman 入户" },
      { label: "素材系列", value: "门4" },
      { label: "处理周期", value: "7–10 个工作日" },
    ],
  },
  m05: {
    name: "五格 Colonial — 底漆",
    description: "全屋换新主力款：五等分面板，上漆后质感接近实木，对标大卖场「订货」线。",
    highlights: ["10 樘 + 运费组合性价比高", "批次间纹理模拟一致", "承包商复购多"],
    leadTime: "6–8 个工作日",
    finish: "底漆",
    size: "全尺寸常备",
    material: "实木芯",
    installation: "单板或 RapidHang™",
    categoryName: "室内门",
    specs: [
      { label: "SKU", value: "DTD-INT-M05" },
      { label: "款式", value: "五面板" },
      { label: "素材系列", value: "门5" },
      { label: "处理周期", value: "6–8 个工作日" },
    ],
  },
  m06: {
    name: "四格底漆 — 标准锁孔",
    description: "传统户型均衡之选 — 最快统一全屋油漆计划。",
    highlights: ["衣帽间与浴室常用", "匹配大量 90–10 年代住宅", "亚特兰大仓有货时发货快"],
    leadTime: "6–8 个工作日",
    finish: "底漆",
    size: "卧室与浴室常用宽",
    material: "MDF 面层 / 实木芯",
    installation: "单板或 RapidHang™",
    categoryName: "室内门",
    specs: [
      { label: "SKU", value: "DTD-INT-M06" },
      { label: "款式", value: "四面板" },
      { label: "素材系列", value: "门6" },
      { label: "处理周期", value: "6–8 个工作日" },
    ],
  },
  m07: {
    name: "宽挺 Shaker — 底漆",
    description: "更宽的框线，在开放餐厨一侧门扇更有「家具感」。",
    highlights: ["开放户型视觉更稳", "搭配黑色拉手趋势", "国际订单可询价打木箱"],
    leadTime: "6–8 个工作日",
    finish: "底漆",
    size: "侧重 32″–36″",
    material: "实木芯",
    installation: "单板或 RapidHang™",
    categoryName: "室内门",
    specs: [
      { label: "SKU", value: "DTD-INT-M07" },
      { label: "款式", value: "宽挺 Shaker" },
      { label: "素材系列", value: "门7" },
      { label: "处理周期", value: "6–8 个工作日" },
    ],
  },
  m08: {
    name: "仿玻璃纤维入户 — 预挂",
    description: "低维护、仿木纹理 — 沿海与高紫外线市场常见（国际运费单询）。",
    highlights: ["相对实木入户更稳胀缩", "可询价保温芯层", "物流专线：freight@doortodoorco.com"],
    leadTime: "7–10 个工作日",
    finish: "工厂面层可选（询价）",
    size: "单开入户标准",
    material: "复合入户系统",
    installation: "预挂",
    categoryName: "室外门（入户）",
    specs: [
      { label: "SKU", value: "DTD-EXT-M08" },
      { label: "款式", value: "仿玻纤入户" },
      { label: "素材系列", value: "门8" },
      { label: "处理周期", value: "7–10 个工作日" },
    ],
  },
  m09: {
    name: "折叠衣柜对开 — 底漆",
    description: "包装紧凑，单人可搬上楼，相比平开门更省摆动空间。",
    highlights: ["洗衣房与衣帽间省开门弧", "可配五金包", "可与室内门同一票货运"],
    leadTime: "6–8 个工作日",
    finish: "底漆",
    size: "最大约 72″ 洞口（请询价确认）",
    material: "空心 / 实心可选",
    installation: "含轨道套件（以说明为准）",
    categoryName: "折叠门",
    specs: [
      { label: "SKU", value: "DTD-BIF-M09" },
      { label: "款式", value: "双扇折叠" },
      { label: "素材系列", value: "门9" },
      { label: "处理周期", value: "6–8 个工作日" },
    ],
  },
  m10: {
    name: "洗衣房折叠 — 窄型",
    description: "针对设备间洞口，立面更干净，与家电并排不抢视觉。",
    highlights: ["比改平开安装更快", "可与百叶 SKU 组成同一 utility 区", "跨境可提供 HS 编码与单证询价"],
    leadTime: "6–8 个工作日",
    finish: "底漆",
    size: "窄洞口",
    material: "轻型框材",
    installation: "折叠五金",
    categoryName: "折叠门",
    specs: [
      { label: "SKU", value: "DTD-BIF-M10" },
      { label: "款式", value: "Utility 折叠" },
      { label: "素材系列", value: "门10" },
      { label: "处理周期", value: "6–8 个工作日" },
    ],
  },
  m11: {
    name: "全百叶 — 底漆",
    description: "机电柜与食品储藏间通风量大，同时保持完成面不「廉价」。",
    highlights: ["设备柜透气", "可漆成与套线同色", "常与 DTD-BIF-M09 同项目下单"],
    leadTime: "6–8 个工作日",
    finish: "底漆",
    size: "衣柜 / 食品间标准",
    material: "透气挺结构",
    installation: "单板或改折叠",
    categoryName: "百叶门",
    specs: [
      { label: "SKU", value: "DTD-LOU-M11" },
      { label: "款式", value: "全百叶" },
      { label: "素材系列", value: "门11" },
      { label: "处理周期", value: "6–8 个工作日" },
    ],
  },
  m12: {
    name: "窄百叶衣柜 — 底漆",
    description: "百叶间距更紧，外立面更克制 — 批量房洗衣套餐常用。",
    highlights: ["比宽百叶视觉更安静", "可与折叠门叠放运输", "亚特兰大自提：jesus@doortodoorco.com"],
    leadTime: "6–8 个工作日",
    finish: "底漆",
    size: "标准衣柜",
    material: "复合百叶",
    installation: "单板",
    categoryName: "百叶门",
    specs: [
      { label: "SKU", value: "DTD-LOU-M12" },
      { label: "款式", value: "窄百叶" },
      { label: "素材系列", value: "门12" },
      { label: "处理周期", value: "6–8 个工作日" },
    ],
  },
};
